export const cityOptions = ["New Delhi", "Mumbai", "Pune", "Bengaluru", "Hyderabad", "Chennai", "Kolkata"];

export const preferenceOptions = [
  "mountains",
  "beach",
  "adventure",
  "peaceful",
  "party",
  "camping",
  "spiritual",
  "trekking",
  "family",
  "hidden"
];

export const transportOptions = [
  ["car", "Self-drive car"],
  ["bike", "Bike trip"],
  ["bus", "Volvo/Bus"],
  ["tempo", "Tempo Traveller"],
  ["trainCab", "Train + Cab"]
];

export const defaultTripInputs = {
  budget: 5000,
  startCity: "New Delhi",
  officeEndTime: "Friday 7 PM",
  duration: "Friday night to Sunday night",
  returnDeadline: "Monday 8 AM",
  groupSize: 6,
  preference: "mountains",
  transport: "car",
  food: "Indian",
  groupStyle: {
    adventure: false,
    party: false,
    relaxation: true,
    photography: true,
    trekking: false
  }
};

export const planningConstants = {
  fuelPrice: 105,
  emergencyMargin: 0.12,
  fridayDepartureHour: 21.5,
  mondayDeadlineHour: 32,
  tempoTravellerPerKm: 36
};

export const transportProfiles = {
  car: {
    label: "Self-drive car",
    mileage: 14,
    seatsPerVehicle: 4,
    timeMultiplier: 1,
    fatigueMultiplier: 1,
    tollMultiplier: 1
  },
  bike: {
    label: "Bike trip",
    mileage: 32,
    seatsPerVehicle: 2,
    timeMultiplier: 1.08,
    fatigueMultiplier: 1.24,
    tollMultiplier: 0.25
  },
  bus: {
    label: "Volvo/Bus",
    timeMultiplier: 1.15,
    fatigueMultiplier: 0.82,
    tollMultiplier: 0
  },
  tempo: {
    label: "Tempo Traveller",
    timeMultiplier: 1.12,
    fatigueMultiplier: 0.9,
    tollMultiplier: 1.25
  },
  trainCab: {
    label: "Train + Cab",
    timeMultiplier: 1.05,
    fatigueMultiplier: 0.72,
    tollMultiplier: 0
  }
};

export const destinations = [
  {
    id: "delhi-bhimtal",
    origin: "New Delhi",
    name: "Bhimtal + Sattal",
    headline: "Lake-side hidden gem",
    distanceKm: 315,
    driveHours: 7.3,
    crowd: 4,
    scenic: 90,
    weather: 84,
    road: 78,
    baseRating: 9,
    hotelPerPerson: 1550,
    foodPerPerson: 950,
    activityPerPerson: 500,
    tollRoundTrip: 920,
    busFareRoundTrip: 1700,
    trainCabFareRoundTrip: 2100,
    tags: ["mountains", "peaceful", "hidden", "family", "nature", "photography"],
    route: ["New Delhi", "Hapur", "Moradabad", "Haldwani", "Bhimtal"],
    stays: ["Bhimtal lake homestay", "Sattal forest stay", "Budget resort split by group"],
    activities: ["Sattal lake loop", "Kayaking", "Cafe by Bhimtal", "Early morning photo walk"],
    weatherNote: "Calmer than Nainital with pleasant mornings and cool nights.",
    roadNote: "Same highway as Nainital, with less last-mile crowd pressure.",
    mapUrl: "https://www.openstreetmap.org/directions?from=New%20Delhi&to=Bhimtal"
  },
  {
    id: "delhi-rishikesh",
    origin: "New Delhi",
    name: "Rishikesh + Shivpuri",
    headline: "Adventure plus camps",
    distanceKm: 245,
    driveHours: 5.8,
    crowd: 7,
    scenic: 84,
    weather: 80,
    road: 86,
    baseRating: 8,
    hotelPerPerson: 1400,
    foodPerPerson: 1000,
    activityPerPerson: 900,
    tollRoundTrip: 780,
    busFareRoundTrip: 1300,
    trainCabFareRoundTrip: 1850,
    tags: ["mountains", "adventure", "camping", "spiritual", "party", "family"],
    route: ["New Delhi", "Meerut", "Muzaffarnagar", "Haridwar", "Shivpuri"],
    stays: ["Shivpuri riverside camp", "Tapovan budget hotel", "Hostel dorm plus private rooms"],
    activities: ["River rafting", "Ganga aarti", "Cafe walk in Tapovan", "Cliffside sunrise"],
    weatherNote: "Pleasant mornings, warmer afternoons near the river.",
    roadNote: "Fast route, but Haridwar weekend traffic needs a strict return start.",
    mapUrl: "https://www.openstreetmap.org/directions?from=New%20Delhi&to=Shivpuri%2C%20Uttarakhand"
  },
  {
    id: "delhi-chakrata",
    origin: "New Delhi",
    name: "Chakrata",
    headline: "Quiet hill escape",
    distanceKm: 330,
    driveHours: 8.5,
    crowd: 3,
    scenic: 91,
    weather: 80,
    road: 70,
    baseRating: 8,
    hotelPerPerson: 1500,
    foodPerPerson: 950,
    activityPerPerson: 500,
    tollRoundTrip: 850,
    busFareRoundTrip: 1850,
    trainCabFareRoundTrip: 2300,
    tags: ["mountains", "hidden", "peaceful", "trekking", "nature", "photography"],
    route: ["New Delhi", "Meerut", "Dehradun", "Kalsi", "Chakrata"],
    stays: ["Chakrata homestay", "Budget mountain lodge", "Forest-view cottage"],
    activities: ["Tiger Falls", "Deoban viewpoint", "Chilmiri Neck", "Local dhaba dinner"],
    weatherNote: "Quiet hill weather; check fog before night movement.",
    roadNote: "Final road is slower and patchier than the distance suggests.",
    mapUrl: "https://www.openstreetmap.org/directions?from=New%20Delhi&to=Chakrata"
  },
  {
    id: "delhi-lansdowne",
    origin: "New Delhi",
    name: "Lansdowne",
    headline: "Low crowd and budget friendly",
    distanceKm: 260,
    driveHours: 6.4,
    crowd: 4,
    scenic: 78,
    weather: 82,
    road: 78,
    baseRating: 6,
    hotelPerPerson: 1300,
    foodPerPerson: 900,
    activityPerPerson: 350,
    tollRoundTrip: 720,
    busFareRoundTrip: 1450,
    trainCabFareRoundTrip: 1900,
    tags: ["mountains", "peaceful", "family", "budget", "photography"],
    route: ["New Delhi", "Meerut", "Bijnor", "Kotdwar", "Lansdowne"],
    stays: ["Army cantonment side hotel", "Budget lodge near Gandhi Chowk", "Forest-edge homestay"],
    activities: ["Bhulla Tal", "Tip-in-Top viewpoint", "War memorial", "Quiet cafe dinner"],
    weatherNote: "Cool nights and manageable daytime walks.",
    roadNote: "Good distance for office-safe return; narrow final hill stretch.",
    mapUrl: "https://www.openstreetmap.org/directions?from=New%20Delhi&to=Lansdowne%2C%20Uttarakhand"
  },
  {
    id: "delhi-kanatal",
    origin: "New Delhi",
    name: "Kanatal",
    headline: "Camping and forest trails",
    distanceKm: 320,
    driveHours: 8,
    crowd: 5,
    scenic: 87,
    weather: 82,
    road: 74,
    baseRating: 7,
    hotelPerPerson: 1500,
    foodPerPerson: 1000,
    activityPerPerson: 850,
    tollRoundTrip: 850,
    busFareRoundTrip: 1700,
    trainCabFareRoundTrip: 2250,
    tags: ["mountains", "adventure", "camping", "trekking", "photography"],
    route: ["New Delhi", "Meerut", "Muzaffarnagar", "Dehradun", "Kanatal"],
    stays: ["Kanatal dome camp", "Dhanaulti budget resort", "Group cottage with bonfire"],
    activities: ["Kaudia forest trail", "Zipline camp activities", "Bonfire", "Dhanaulti eco park"],
    weatherNote: "Cold after sunset; camps need warm layers.",
    roadNote: "Longer hill section makes Sunday return planning important.",
    mapUrl: "https://www.openstreetmap.org/directions?from=New%20Delhi&to=Kanatal"
  },
  {
    id: "mumbai-lonavala",
    origin: "Mumbai",
    name: "Lonavala + Pawna",
    headline: "Camping close to the city",
    distanceKm: 85,
    driveHours: 2.4,
    crowd: 8,
    scenic: 76,
    weather: 78,
    road: 88,
    baseRating: 7,
    hotelPerPerson: 1400,
    foodPerPerson: 950,
    activityPerPerson: 650,
    tollRoundTrip: 650,
    busFareRoundTrip: 850,
    trainCabFareRoundTrip: 950,
    tags: ["camping", "party", "family", "peaceful", "roadtrip"],
    route: ["Mumbai", "Panvel", "Khalapur", "Lonavala", "Pawna"],
    stays: ["Pawna lakeside camp", "Lonavala group villa", "Budget resort near Tungarli"],
    activities: ["Pawna lake sunset", "Tiger Point", "Bhushi Dam walk", "Campfire dinner"],
    weatherNote: "Mild evenings; monsoon months need rain checks.",
    roadNote: "Expressway is fast, but Saturday traffic can be heavy.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Mumbai&to=Pawna%20Lake"
  },
  {
    id: "mumbai-alibaug",
    origin: "Mumbai",
    name: "Alibaug",
    headline: "Beach weekend without flight planning",
    distanceKm: 105,
    driveHours: 3.2,
    crowd: 7,
    scenic: 74,
    weather: 80,
    road: 82,
    baseRating: 7,
    hotelPerPerson: 1700,
    foodPerPerson: 1100,
    activityPerPerson: 450,
    tollRoundTrip: 520,
    busFareRoundTrip: 900,
    trainCabFareRoundTrip: 1350,
    tags: ["beach", "party", "family", "peaceful", "hidden"],
    route: ["Mumbai", "Panvel", "Pen", "Alibaug"],
    stays: ["Nagaon beach homestay", "Alibaug budget villa", "Kihim cottage"],
    activities: ["Nagaon beach", "Kolaba Fort", "Seafood lunch", "Kihim sunset"],
    weatherNote: "Humid afternoons; early beach slots are better.",
    roadNote: "Ferry can save time if weather and luggage allow.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Mumbai&to=Alibaug"
  },
  {
    id: "mumbai-igatpuri",
    origin: "Mumbai",
    name: "Igatpuri",
    headline: "Easy mountain air",
    distanceKm: 125,
    driveHours: 3.1,
    crowd: 5,
    scenic: 82,
    weather: 78,
    road: 84,
    baseRating: 7,
    hotelPerPerson: 1500,
    foodPerPerson: 950,
    activityPerPerson: 500,
    tollRoundTrip: 760,
    busFareRoundTrip: 950,
    trainCabFareRoundTrip: 1200,
    tags: ["mountains", "peaceful", "trekking", "family", "hidden"],
    route: ["Mumbai", "Thane", "Kasara", "Igatpuri"],
    stays: ["Kasara valley homestay", "Budget resort near Bhatsa", "Igatpuri villa split"],
    activities: ["Camel Valley", "Vaitarna viewpoints", "Vipassana pagoda", "Local thali dinner"],
    weatherNote: "Cooler than Mumbai, especially around lakes and valleys.",
    roadNote: "Ghat road is manageable; avoid late-night speeding.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Mumbai&to=Igatpuri"
  },
  {
    id: "mumbai-mahabaleshwar",
    origin: "Mumbai",
    name: "Mahabaleshwar",
    headline: "Classic hill station stretch",
    distanceKm: 260,
    driveHours: 6.3,
    crowd: 8,
    scenic: 86,
    weather: 76,
    road: 78,
    baseRating: 7,
    hotelPerPerson: 1900,
    foodPerPerson: 1100,
    activityPerPerson: 650,
    tollRoundTrip: 1150,
    busFareRoundTrip: 1600,
    trainCabFareRoundTrip: 2300,
    tags: ["mountains", "family", "party", "photography", "roadtrip"],
    route: ["Mumbai", "Pune", "Wai", "Panchgani", "Mahabaleshwar"],
    stays: ["Panchgani budget hotel", "Mahabaleshwar homestay", "Group villa outside market"],
    activities: ["Arthur Seat", "Mapro Garden", "Venna Lake", "Sunset Point"],
    weatherNote: "Good hill weather; fog and rain can affect viewpoints.",
    roadNote: "Return can choke near Panchgani and Pune bypass.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Mumbai&to=Mahabaleshwar"
  },
  {
    id: "mumbai-nashik",
    origin: "Mumbai",
    name: "Nashik + Trimbak",
    headline: "Spiritual plus vineyard break",
    distanceKm: 170,
    driveHours: 4,
    crowd: 6,
    scenic: 76,
    weather: 78,
    road: 86,
    baseRating: 7,
    hotelPerPerson: 1500,
    foodPerPerson: 1050,
    activityPerPerson: 550,
    tollRoundTrip: 820,
    busFareRoundTrip: 1000,
    trainCabFareRoundTrip: 1500,
    tags: ["spiritual", "family", "party", "peaceful", "hidden"],
    route: ["Mumbai", "Thane", "Kasara", "Nashik", "Trimbak"],
    stays: ["Nashik city hotel", "Vineyard-side stay", "Trimbak budget lodge"],
    activities: ["Trimbakeshwar temple", "Sula sunset", "Pandavleni caves", "Misal breakfast"],
    weatherNote: "Dry and pleasant evenings outside peak summer.",
    roadNote: "Highway is strong; temple queues can affect timing.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Mumbai&to=Nashik"
  },
  {
    id: "pune-mulshi",
    origin: "Pune",
    name: "Mulshi + Tamhini",
    headline: "Short scenic reset",
    distanceKm: 55,
    driveHours: 1.8,
    crowd: 5,
    scenic: 82,
    weather: 80,
    road: 76,
    baseRating: 8,
    hotelPerPerson: 1450,
    foodPerPerson: 900,
    activityPerPerson: 350,
    tollRoundTrip: 180,
    busFareRoundTrip: 650,
    trainCabFareRoundTrip: 900,
    tags: ["peaceful", "hidden", "camping", "family", "roadtrip"],
    route: ["Pune", "Pirangut", "Mulshi", "Tamhini"],
    stays: ["Mulshi lake homestay", "Tamhini eco camp", "Budget farm stay"],
    activities: ["Mulshi lake view", "Tamhini forest drive", "Waterfall stop", "Simple lakeside dinner"],
    weatherNote: "Excellent in monsoon and winter; afternoons stay mild near water.",
    roadNote: "Road narrows in Tamhini; daylight movement is better.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Pune&to=Mulshi"
  },
  {
    id: "pune-mahabaleshwar",
    origin: "Pune",
    name: "Mahabaleshwar + Panchgani",
    headline: "Family-friendly hill classic",
    distanceKm: 120,
    driveHours: 3.3,
    crowd: 8,
    scenic: 86,
    weather: 76,
    road: 80,
    baseRating: 7,
    hotelPerPerson: 1750,
    foodPerPerson: 1000,
    activityPerPerson: 650,
    tollRoundTrip: 520,
    busFareRoundTrip: 900,
    trainCabFareRoundTrip: 1450,
    tags: ["mountains", "family", "party", "photography", "roadtrip"],
    route: ["Pune", "Wai", "Panchgani", "Mahabaleshwar"],
    stays: ["Panchgani budget hotel", "Mahabaleshwar market stay", "Group villa outside town"],
    activities: ["Table Land", "Mapro Garden", "Venna Lake", "Arthur Seat"],
    weatherNote: "Cool nights; fog is possible after sunset.",
    roadNote: "Crowd and parking are the biggest friction points.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Pune&to=Mahabaleshwar"
  },
  {
    id: "pune-alibaug",
    origin: "Pune",
    name: "Alibaug + Nagaon",
    headline: "Beach plan from Pune",
    distanceKm: 145,
    driveHours: 4,
    crowd: 7,
    scenic: 74,
    weather: 80,
    road: 80,
    baseRating: 7,
    hotelPerPerson: 1700,
    foodPerPerson: 1100,
    activityPerPerson: 450,
    tollRoundTrip: 620,
    busFareRoundTrip: 1100,
    trainCabFareRoundTrip: 1650,
    tags: ["beach", "party", "family", "peaceful"],
    route: ["Pune", "Tamhini", "Mangaon", "Alibaug"],
    stays: ["Nagaon homestay", "Alibaug budget villa", "Kihim beach cottage"],
    activities: ["Nagaon beach", "Kolaba Fort", "Seafood lunch", "Kihim sunset"],
    weatherNote: "Humid afternoons; beach plans work best early and late.",
    roadNote: "Tamhini route is scenic but slower after dark.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Pune&to=Alibaug"
  },
  {
    id: "pune-bhandardara",
    origin: "Pune",
    name: "Bhandardara",
    headline: "Lake camping and stargazing",
    distanceKm: 170,
    driveHours: 4.8,
    crowd: 4,
    scenic: 88,
    weather: 78,
    road: 72,
    baseRating: 8,
    hotelPerPerson: 1350,
    foodPerPerson: 900,
    activityPerPerson: 500,
    tollRoundTrip: 520,
    busFareRoundTrip: 1300,
    trainCabFareRoundTrip: 1900,
    tags: ["camping", "peaceful", "hidden", "trekking", "nature"],
    route: ["Pune", "Narayangaon", "Sangamner", "Bhandardara"],
    stays: ["Arthur Lake camp", "Budget village homestay", "Lakeside tent stay"],
    activities: ["Arthur Lake", "Randha Falls", "Kalsubai base visit", "Stargazing"],
    weatherNote: "Cooler near the lake; camps need layers in winter.",
    roadNote: "Last stretch is slower; return before evening traffic builds.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Pune&to=Bhandardara"
  },
  {
    id: "bengaluru-coorg",
    origin: "Bengaluru",
    name: "Coorg",
    headline: "Coffee estates and waterfalls",
    distanceKm: 260,
    driveHours: 6.2,
    crowd: 7,
    scenic: 90,
    weather: 82,
    road: 78,
    baseRating: 8,
    hotelPerPerson: 1750,
    foodPerPerson: 1050,
    activityPerPerson: 650,
    tollRoundTrip: 720,
    busFareRoundTrip: 1450,
    trainCabFareRoundTrip: 2100,
    tags: ["mountains", "peaceful", "family", "adventure", "photography"],
    route: ["Bengaluru", "Mysuru", "Kushalnagar", "Madikeri"],
    stays: ["Madikeri homestay", "Coffee estate stay", "Budget lodge near town"],
    activities: ["Abbey Falls", "Raja Seat", "Coffee estate walk", "Local Kodava dinner"],
    weatherNote: "Pleasant most weekends; rain can make waterfalls better but roads slower.",
    roadNote: "Mysuru road is strong; final hill stretch needs patience.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Bengaluru&to=Madikeri"
  },
  {
    id: "bengaluru-chikmagalur",
    origin: "Bengaluru",
    name: "Chikmagalur",
    headline: "Trekking and coffee views",
    distanceKm: 245,
    driveHours: 5.6,
    crowd: 6,
    scenic: 92,
    weather: 80,
    road: 78,
    baseRating: 8,
    hotelPerPerson: 1650,
    foodPerPerson: 1000,
    activityPerPerson: 700,
    tollRoundTrip: 680,
    busFareRoundTrip: 1350,
    trainCabFareRoundTrip: 2050,
    tags: ["mountains", "trekking", "adventure", "peaceful", "photography"],
    route: ["Bengaluru", "Hassan", "Belur", "Chikmagalur"],
    stays: ["Coffee estate homestay", "Budget town hotel", "Hill-view cottage"],
    activities: ["Mullayanagiri sunrise", "Baba Budangiri", "Coffee estate walk", "Cafe dinner"],
    weatherNote: "Cool mornings; windy viewpoints need layers.",
    roadNote: "Hill viewpoints get crowded; start early Sunday.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Bengaluru&to=Chikmagalur"
  },
  {
    id: "bengaluru-wayanad",
    origin: "Bengaluru",
    name: "Wayanad",
    headline: "Forest and waterfall weekend",
    distanceKm: 280,
    driveHours: 6.8,
    crowd: 6,
    scenic: 88,
    weather: 82,
    road: 74,
    baseRating: 8,
    hotelPerPerson: 1600,
    foodPerPerson: 950,
    activityPerPerson: 650,
    tollRoundTrip: 620,
    busFareRoundTrip: 1500,
    trainCabFareRoundTrip: 2200,
    tags: ["forest", "adventure", "peaceful", "family", "hidden"],
    route: ["Bengaluru", "Mysuru", "Gundlupet", "Sultan Bathery"],
    stays: ["Kalpetta homestay", "Forest-edge resort", "Budget villa split"],
    activities: ["Pookode Lake", "Edakkal Caves", "Soochipara Falls", "Kerala dinner"],
    weatherNote: "Lush and cool, especially after rains.",
    roadNote: "Forest gates and speed limits affect timing.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Bengaluru&to=Wayanad"
  },
  {
    id: "bengaluru-pondicherry",
    origin: "Bengaluru",
    name: "Pondicherry",
    headline: "Beach, cafes, and easy nightlife",
    distanceKm: 315,
    driveHours: 6.5,
    crowd: 8,
    scenic: 78,
    weather: 78,
    road: 82,
    baseRating: 7,
    hotelPerPerson: 1700,
    foodPerPerson: 1150,
    activityPerPerson: 550,
    tollRoundTrip: 760,
    busFareRoundTrip: 1450,
    trainCabFareRoundTrip: 2100,
    tags: ["beach", "party", "spiritual", "family", "cafes"],
    route: ["Bengaluru", "Krishnagiri", "Tiruvannamalai", "Pondicherry"],
    stays: ["White Town guesthouse", "Auroville budget stay", "Beach road hotel"],
    activities: ["Promenade walk", "Auroville visit", "Serenity Beach", "French cafe dinner"],
    weatherNote: "Humid afternoons; morning beach plans are best.",
    roadNote: "Good highway, but city parking gets tight.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Bengaluru&to=Pondicherry"
  },
  {
    id: "hyderabad-srisailam",
    origin: "Hyderabad",
    name: "Srisailam",
    headline: "Spiritual forest road trip",
    distanceKm: 215,
    driveHours: 5.2,
    crowd: 6,
    scenic: 82,
    weather: 76,
    road: 74,
    baseRating: 7,
    hotelPerPerson: 1250,
    foodPerPerson: 850,
    activityPerPerson: 450,
    tollRoundTrip: 520,
    busFareRoundTrip: 950,
    trainCabFareRoundTrip: 1700,
    tags: ["spiritual", "forest", "family", "peaceful", "roadtrip"],
    route: ["Hyderabad", "Kalwakurthy", "Dindi", "Srisailam"],
    stays: ["Temple town lodge", "Forest guesthouse", "Budget hotel near dam"],
    activities: ["Mallikarjuna temple", "Srisailam dam", "Ropeway view", "Simple Andhra dinner"],
    weatherNote: "Warm afternoons; evenings near the dam are better.",
    roadNote: "Forest road has speed controls and limited late-night movement.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Hyderabad&to=Srisailam"
  },
  {
    id: "hyderabad-anantagiri",
    origin: "Hyderabad",
    name: "Ananthagiri Hills",
    headline: "Lowest-friction green break",
    distanceKm: 85,
    driveHours: 2.2,
    crowd: 5,
    scenic: 74,
    weather: 76,
    road: 80,
    baseRating: 6,
    hotelPerPerson: 1150,
    foodPerPerson: 850,
    activityPerPerson: 350,
    tollRoundTrip: 240,
    busFareRoundTrip: 550,
    trainCabFareRoundTrip: 850,
    tags: ["peaceful", "trekking", "family", "hidden", "camping"],
    route: ["Hyderabad", "Chevella", "Vikarabad", "Ananthagiri"],
    stays: ["Vikarabad budget resort", "Forest-edge camp", "Simple farm stay"],
    activities: ["Ananthagiri forest walk", "Kotepally reservoir", "Sunset point", "Local dinner"],
    weatherNote: "Best after rains; summer afternoons are warm.",
    roadNote: "Short and safe, ideal when Monday fatigue must stay low.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Hyderabad&to=Ananthagiri%20Hills"
  },
  {
    id: "hyderabad-hampi",
    origin: "Hyderabad",
    name: "Hampi",
    headline: "Heritage plus boulders",
    distanceKm: 375,
    driveHours: 8.5,
    crowd: 6,
    scenic: 88,
    weather: 72,
    road: 78,
    baseRating: 8,
    hotelPerPerson: 1500,
    foodPerPerson: 950,
    activityPerPerson: 550,
    tollRoundTrip: 950,
    busFareRoundTrip: 1850,
    trainCabFareRoundTrip: 2100,
    tags: ["hidden", "spiritual", "adventure", "party", "photography"],
    route: ["Hyderabad", "Kurnool", "Ballari", "Hampi"],
    stays: ["Hampi bazaar guesthouse", "Sanapur budget stay", "Group homestay"],
    activities: ["Virupaksha temple", "Boulder sunset", "Coracle ride", "Cafe dinner in Sanapur"],
    weatherNote: "Hot afternoons; sunrise and sunset slots matter.",
    roadNote: "Feasible but tiring; train plus cab is often smarter.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Hyderabad&to=Hampi"
  },
  {
    id: "chennai-pondicherry",
    origin: "Chennai",
    name: "Pondicherry",
    headline: "Beach and cafe classic",
    distanceKm: 155,
    driveHours: 3.5,
    crowd: 8,
    scenic: 78,
    weather: 78,
    road: 84,
    baseRating: 7,
    hotelPerPerson: 1650,
    foodPerPerson: 1100,
    activityPerPerson: 500,
    tollRoundTrip: 420,
    busFareRoundTrip: 700,
    trainCabFareRoundTrip: 1000,
    tags: ["beach", "party", "spiritual", "family", "cafes"],
    route: ["Chennai", "ECR", "Mahabalipuram", "Pondicherry"],
    stays: ["White Town guesthouse", "Auroville budget stay", "Beach road hotel"],
    activities: ["Promenade walk", "Auroville visit", "Serenity Beach", "French cafe dinner"],
    weatherNote: "Humid afternoons; keep beach walks for morning and sunset.",
    roadNote: "ECR is scenic and straightforward, but weekend entry is crowded.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Chennai&to=Pondicherry"
  },
  {
    id: "chennai-yelagiri",
    origin: "Chennai",
    name: "Yelagiri",
    headline: "Easy hill station for families",
    distanceKm: 230,
    driveHours: 4.8,
    crowd: 5,
    scenic: 76,
    weather: 78,
    road: 82,
    baseRating: 6,
    hotelPerPerson: 1300,
    foodPerPerson: 850,
    activityPerPerson: 400,
    tollRoundTrip: 560,
    busFareRoundTrip: 900,
    trainCabFareRoundTrip: 1300,
    tags: ["mountains", "family", "peaceful", "trekking", "budget"],
    route: ["Chennai", "Vellore", "Vaniyambadi", "Yelagiri"],
    stays: ["Yelagiri budget resort", "Hill-view homestay", "Family cottage"],
    activities: ["Punganur Lake", "Swamimalai trail", "Nature park", "Simple hill dinner"],
    weatherNote: "Milder than Chennai, especially at night.",
    roadNote: "Good highway with a manageable final ghat section.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Chennai&to=Yelagiri"
  },
  {
    id: "chennai-tiruvannamalai",
    origin: "Chennai",
    name: "Tiruvannamalai",
    headline: "Spiritual weekend with hill energy",
    distanceKm: 195,
    driveHours: 4.2,
    crowd: 6,
    scenic: 78,
    weather: 76,
    road: 80,
    baseRating: 8,
    hotelPerPerson: 1250,
    foodPerPerson: 850,
    activityPerPerson: 350,
    tollRoundTrip: 420,
    busFareRoundTrip: 750,
    trainCabFareRoundTrip: 1150,
    tags: ["spiritual", "peaceful", "trekking", "family", "hidden"],
    route: ["Chennai", "Tindivanam", "Gingee", "Tiruvannamalai"],
    stays: ["Ashram-side guesthouse", "Budget lodge near temple", "Quiet homestay outside town"],
    activities: ["Arunachaleswarar temple", "Girivalam route walk", "Ramana Ashram", "Hill-view dinner"],
    weatherNote: "Warm afternoons; temple and hill walks are best early morning or evening.",
    roadNote: "Road is reliable, but temple crowd can slow local movement.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Chennai&to=Tiruvannamalai"
  },
  {
    id: "chennai-kodaikanal",
    origin: "Chennai",
    name: "Kodaikanal",
    headline: "Beautiful but aggressive weekend",
    distanceKm: 525,
    driveHours: 10.5,
    crowd: 8,
    scenic: 92,
    weather: 76,
    road: 74,
    baseRating: 8,
    hotelPerPerson: 1750,
    foodPerPerson: 1000,
    activityPerPerson: 650,
    tollRoundTrip: 980,
    busFareRoundTrip: 1900,
    trainCabFareRoundTrip: 2400,
    tags: ["mountains", "family", "party", "photography", "trekking"],
    route: ["Chennai", "Trichy", "Dindigul", "Kodaikanal"],
    stays: ["Lake-side budget hotel", "Vattakanal guesthouse", "Group cottage"],
    activities: ["Coaker's Walk", "Pine forest", "Vattakanal cafes", "Kodaikanal Lake"],
    weatherNote: "Cool and misty, but rain can slow hill roads.",
    roadNote: "High fatigue; train or bus is safer for a Monday office return.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Chennai&to=Kodaikanal"
  },
  {
    id: "kolkata-mandarmani",
    origin: "Kolkata",
    name: "Mandarmani",
    headline: "Beach weekend with low planning load",
    distanceKm: 170,
    driveHours: 4.2,
    crowd: 7,
    scenic: 74,
    weather: 78,
    road: 80,
    baseRating: 7,
    hotelPerPerson: 1500,
    foodPerPerson: 950,
    activityPerPerson: 400,
    tollRoundTrip: 480,
    busFareRoundTrip: 850,
    trainCabFareRoundTrip: 1250,
    tags: ["beach", "party", "family", "peaceful"],
    route: ["Kolkata", "Kolaghat", "Nandakumar", "Mandarmani"],
    stays: ["Mandarmani beach resort", "Budget sea-facing hotel", "Group cottage"],
    activities: ["Beach walk", "Seafood lunch", "Digha side trip", "Sunset by the shore"],
    weatherNote: "Humid but breezy near the water.",
    roadNote: "Road is manageable; avoid late Sunday beach exit.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Kolkata&to=Mandarmani"
  },
  {
    id: "kolkata-shantiniketan",
    origin: "Kolkata",
    name: "Shantiniketan",
    headline: "Culture, calm, and food",
    distanceKm: 165,
    driveHours: 4.1,
    crowd: 5,
    scenic: 72,
    weather: 76,
    road: 78,
    baseRating: 7,
    hotelPerPerson: 1350,
    foodPerPerson: 900,
    activityPerPerson: 350,
    tollRoundTrip: 420,
    busFareRoundTrip: 700,
    trainCabFareRoundTrip: 950,
    tags: ["peaceful", "family", "hidden", "spiritual", "budget"],
    route: ["Kolkata", "Bardhaman", "Bolpur", "Shantiniketan"],
    stays: ["Bolpur homestay", "Budget guesthouse", "Baul-themed resort"],
    activities: ["Visva-Bharati campus", "Sonajhuri haat", "Baul music evening", "Bengali lunch"],
    weatherNote: "Comfortable outside peak summer; winter weekends are best.",
    roadNote: "Train plus cab can beat road fatigue.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Kolkata&to=Shantiniketan"
  },
  {
    id: "kolkata-ajodhya",
    origin: "Kolkata",
    name: "Ajodhya Hills",
    headline: "Hidden hills and forest roads",
    distanceKm: 315,
    driveHours: 7.2,
    crowd: 4,
    scenic: 84,
    weather: 76,
    road: 70,
    baseRating: 7,
    hotelPerPerson: 1250,
    foodPerPerson: 850,
    activityPerPerson: 450,
    tollRoundTrip: 650,
    busFareRoundTrip: 1250,
    trainCabFareRoundTrip: 1700,
    tags: ["hidden", "mountains", "forest", "trekking", "peaceful"],
    route: ["Kolkata", "Durgapur", "Purulia", "Ajodhya Hills"],
    stays: ["Purulia lodge", "Ajodhya hill homestay", "Forest-side budget stay"],
    activities: ["Upper Dam viewpoint", "Bamni Falls", "Hill road drive", "Local dinner"],
    weatherNote: "Dry and pleasant in winter; summer heat is tiring.",
    roadNote: "Longer drive and patchy last stretch need early return.",
    mapUrl: "https://www.openstreetmap.org/directions?from=Kolkata&to=Ajodhya%20Hills"
  }
];
